# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build a new app using match"
  lane :beta do
    build_app(scheme: "MatchSigning")
    #upload_to_testflight
  end

  desc "Build a new app using match"
  lane :alpha do
    install_profiles_locally

    update_code_signing_settings(
      code_sign_identity: 'iPhone Distribution',
      profile_name: "match AppStore com.allyouzombies.MatchSigning"
    )

    build_app(scheme: "MatchSigning")
    #upload_to_testflight
  end

  desc "Updated code sign details"
  lane :update_signing do
    install_profiles_locally

    update_code_signing_settings(
      code_sign_identity: 'iPhone Distribution',
      profile_name: "match AppStore com.allyouzombies.MatchSigning"
    )
  end

  desc "Install profiles locally"
  lane :install_profiles_locally do
    match(
      type: 'appstore'
    )
  end
end
